export let products = [
  {
    title: "Cintas express 15cm",
    price: 300000,
    stock: 6,
    description: "Black diamond",
    category: "Deportiva",
    img: "https://www.bfgcdn.com/1500_1500_90/319-0388/black-diamond-miniwire-quickpack-quickdraw.jpg",
  },
  {
    title: "Camalot #0.5",
    price: 150000,
    stock: 4,
    description: "black diamond",
    category: "Clásica",
    img: "https://cdn11.bigcommerce.com/s-hgn1l9sh63/images/stencil/1000w/attribute_rule_images/9097_source_1687931236.png",
  },
  {
    title: "Stoppers set",
    price: 60000,
    stock: 1,
    description: "wild country",
    category: "Clásica",
    img: "https://www.suescalada.com/4127-thickbox_default/rock-set-1-10-stoppers-wild-country-.jpg",
  },
  {
    title: "Vector Helmet",
    price: 300000,
    stock: 1,
    description: "Black diamond",
    category: "Otros",
    img: "https://content.steepandcheap.com/images/items/900/BLD/BLD1409/OCT.jpg",
  },
  {
    title: "Index Ascender",
    price: 350000,
    stock: 5,
    description: "Black diamond",
    category: "Otros",
    img: "https://content.steepandcheap.com/images/items/900/BLD/BLD00BN/BDOR.jpg",
  },
  {
    title: "Zero friend set 0.4-0.75",
    price: 1200000,
    stock: 2,
    description: "wild country",
    category: "Clásica",
    img: "https://www.wildcountry.com/media/image/b1/d1/50/d2b6cf34-822f-4bc7-8c9e-ed6e859dee9b_wildcountry_350x350@2x.jpg",
  },
  {
    title: "Tommy Caldwell Pro Dry DT Climbing Rope - 9.6mm",
    price: 700000,
    stock: 4,
    description: "Edelrid",
    category: "Otros",
    img: "https://res.cloudinary.com/drr0x3v88/image/upload/v1691210718/React%20-%20rock%20climbing%20ecommerce/NEOGN_en2zfi.avif",
  },
];